# Tomcat
server:
    tomcat:
        uri-encoding: UTF-8
    port: 10001
    context-path: /
logging:
  level:
    com.poetry.modules.poetry.dao : debug
# mysql
spring:
    jmx:
        default-domain: order-server
    # 环境 dev|test|pro
    profiles:
        active: dev
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
    # jackson时间格式化
    jackson:
        time-zone: GMT+8
        date-format: yyyy-MM-dd HH:mm:ss
    servlet:
        multipart:
            max-file-size: 100MB
            max-request-size: 100MB
            enabled: true
    # 指定静态资源的路径
    web:
        resources:
            static-locations: classpath:/static/,classpath:/views/,file:${fileupload.filepath}

# Mybatis配置
mybatis:
    mapperLocations: classpath:mapper/**/*.xml
    configLocation: classpath:mybatis.xml


#jwt配置
jwt:
    # 加密秘钥
    secret: b65vhvpob8kw5qnuh09rihdjscja4ecw[www.wfuhui.com]
    # token有效时长，7天，单位秒
    expire: 604800
    header: token

#小程序配置
wechat:
  miniapp:
    appid: wx5c8f5b8d3fbc55b7
    secret: 3e0e796d4defd7543091d4b85f4db741
    token:
    aesKey:
    msgDataFormat: JSON
  pay:
    appId: xxxxxxxx
    mchId:
    mchKey:
    subAppId:
    subMchId:
    keyPath:
    notifyUrl: https://x.com/api/wechat/pay/parseOrderNotifyResult